CC := gcc
TARGET :=  hello-makefile.out
OBJS :=  func.o main.o const.o

$(TARGET) : $(OBJS)
	$(CC) -o $@ $^
	
$(OBJS) : %.o : %.c
	$(CC) -o $@ -c $^

.PHNOY : rebuild clean all

rebuild :
	clean all

all : $(TARGET)

clean :
	$(RM) *.o $(TARGET)
